spring:
  application:
    name: backend

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


clerk:
  issuer: ${CLERK_ISSUER}
  jwks-url: ${CLERK_JWKS_URL}

frontend:
  url: ${FRONTEND_URL}